title: Multivariate Statistics with Python
author: Micha Burkhardt
logo: logo.png

# Reference: https://jupyterbook.org/en/stable/customize/config.html

# Do not execute notebooks
execute:
  execute_notebooks: "auto"
  exclude_patterns: ["*.ipynb", "book/statistics/6_EFA/2_factor_analyzer.md", "book/statistics/7_CFA_SEM/3_Semopy.md", "book/statistics/8_Polynomial_Reg/3_Statsmodels.md", "book/statistics/10_Multilevel_Models/2_Statsmodels.md"]

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - book/misc/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/mibur1/psy111-book
  branch: main

# Add GitHub buttons to your book
html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  baseurl: https://mibur1.github.io/psy111-book/
  extra_css:
    - _static/custom.css

sphinx:
  html_context:
    default_mode: dark

# Google colab launch button
launch_buttons:
  colab_url: "https://colab.research.google.com"